// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: currency.sql

package db

import (
	"context"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT rate FROM currencies
WHERE currency = $1 LIMIT 1
`

func (q *Queries) GetExchangeRate(ctx context.Context, currency string) (float64, error) {
	row := q.db.QueryRow(ctx, getExchangeRate, currency)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}
