apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eks-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-3
      auth:
        jwt:
          serviceAccountRef:
            name: eks-external-secrets-irsa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: eks-secret
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: go2bank
---