name: Deploy to production

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-3
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubActionsDeploy

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY_SERVER: go2bank
          REPOSITORY_CRAWLER: go2bank-crawler
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY_SERVER:$IMAGE_TAG -t $REGISTRY/$REPOSITORY_SERVER:latest .
          docker push $REGISTRY/$REPOSITORY_SERVER
          docker build -t $REGISTRY/$REPOSITORY_CRAWLER:$IMAGE_TAG -t $REGISTRY/$REPOSITORY_CRAWLER:latest crawl/
          docker push $REGISTRY/$REPOSITORY_CRAWLER

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install-kubectl
        
      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        id: install-helm

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xzf -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # - name: Create EKS Cluster
      #   run: |
      #     eksctl create cluster -f k8s/eks-cluster.yaml

      - name: Update kube config
        run: aws eks update-kubeconfig --name go2bank --region ap-northeast-3

      - name: Install External Secrets Operator
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm install external-secrets \
            external-secrets/external-secrets \
             -n external-secrets \
             --create-namespace \

      - name: Create EKS OIDC and IRSA
        run: |
          eksctl utils associate-iam-oidc-provider --cluster=go2bank --approve --region ap-northeast-3
          eksctl create iamserviceaccount \
            --name external-secrets-irsa  \
            --namespace default \
            --cluster go2bank \
            --region ap-northeast-3
            --role-name "external-secrets-irsa-role" \
            --attach-policy-arn ${{ secrets.IRSA_POLICY_ARN }}\
            --approve \
            --override-existing-serviceaccounts
          
      - name: Deploy image to Amazon EKS
        run: |
          chmod +x k8s/deploy/install.sh
          k8s/deploy/install.sh
